package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BonusCardType generated by hbm2java
 */
@Entity
@Table(name = "bonus_card_type", catalog = "wuyitech")
public class BonusCardType implements java.io.Serializable {

	private Long id;
	private String cardName;
	private BigDecimal money;
	private BigDecimal minUseMoney;
	private Date sendStartDate;
	private String sendEndDate;
	private Date startDate;
	private Date endDate;
	private String imageUrl;
	private Integer maxAmount;
	private Integer currentAmount;
	private Set<BonusCard> bonusCards = new HashSet<BonusCard>(0);

	public BonusCardType() {
	}

	public BonusCardType(String cardName, BigDecimal money,
			BigDecimal minUseMoney, Date sendStartDate, String sendEndDate,
			Date startDate, Date endDate, String imageUrl, Integer maxAmount,
			Integer currentAmount, Set<BonusCard> bonusCards) {
		this.cardName = cardName;
		this.money = money;
		this.minUseMoney = minUseMoney;
		this.sendStartDate = sendStartDate;
		this.sendEndDate = sendEndDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.imageUrl = imageUrl;
		this.maxAmount = maxAmount;
		this.currentAmount = currentAmount;
		this.bonusCards = bonusCards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "card_name")
	public String getCardName() {
		return this.cardName;
	}

	public void setCardName(String cardName) {
		this.cardName = cardName;
	}

	@Column(name = "money", precision = 10)
	public BigDecimal getMoney() {
		return this.money;
	}

	public void setMoney(BigDecimal money) {
		this.money = money;
	}

	@Column(name = "min_use_money", precision = 10)
	public BigDecimal getMinUseMoney() {
		return this.minUseMoney;
	}

	public void setMinUseMoney(BigDecimal minUseMoney) {
		this.minUseMoney = minUseMoney;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "send_start_date", length = 19)
	public Date getSendStartDate() {
		return this.sendStartDate;
	}

	public void setSendStartDate(Date sendStartDate) {
		this.sendStartDate = sendStartDate;
	}

	@Column(name = "send_end_date", length = 45)
	public String getSendEndDate() {
		return this.sendEndDate;
	}

	public void setSendEndDate(String sendEndDate) {
		this.sendEndDate = sendEndDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "max_amount")
	public Integer getMaxAmount() {
		return this.maxAmount;
	}

	public void setMaxAmount(Integer maxAmount) {
		this.maxAmount = maxAmount;
	}

	@Column(name = "current_amount")
	public Integer getCurrentAmount() {
		return this.currentAmount;
	}

	public void setCurrentAmount(Integer currentAmount) {
		this.currentAmount = currentAmount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bonusCardType")
	public Set<BonusCard> getBonusCards() {
		return this.bonusCards;
	}

	public void setBonusCards(Set<BonusCard> bonusCards) {
		this.bonusCards = bonusCards;
	}

}
