package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "wuyitech")
public class City implements java.io.Serializable {

	private Long id;
	private String name;
	private String state;
	private Set<OrderInfo> orderInfos = new HashSet<OrderInfo>(0);
	private Set<LivingArea> livingAreas = new HashSet<LivingArea>(0);

	public City() {
	}

	public City(String name, String state, Set<OrderInfo> orderInfos,
			Set<LivingArea> livingAreas) {
		this.name = name;
		this.state = state;
		this.orderInfos = orderInfos;
		this.livingAreas = livingAreas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<OrderInfo> getOrderInfos() {
		return this.orderInfos;
	}

	public void setOrderInfos(Set<OrderInfo> orderInfos) {
		this.orderInfos = orderInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<LivingArea> getLivingAreas() {
		return this.livingAreas;
	}

	public void setLivingAreas(Set<LivingArea> livingAreas) {
		this.livingAreas = livingAreas;
	}

}
