package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Complaint generated by hbm2java
 */
@Entity
@Table(name = "complaint", catalog = "wuyitech")
public class Complaint implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private String name;
	private String content;
	private Date createDate;
	private String state;
	private String processState;
	private Set<ComplaintHistory> complaintHistories = new HashSet<ComplaintHistory>(
			0);

	public Complaint() {
	}

	public Complaint(Customer customer, String name, String content,
			Date createDate, String state, String processState,
			Set<ComplaintHistory> complaintHistories) {
		this.customer = customer;
		this.name = name;
		this.content = content;
		this.createDate = createDate;
		this.state = state;
		this.processState = processState;
		this.complaintHistories = complaintHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "content", length = 5000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "process_state", length = 45)
	public String getProcessState() {
		return this.processState;
	}

	public void setProcessState(String processState) {
		this.processState = processState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "complaint")
	public Set<ComplaintHistory> getComplaintHistories() {
		return this.complaintHistories;
	}

	public void setComplaintHistories(Set<ComplaintHistory> complaintHistories) {
		this.complaintHistories = complaintHistories;
	}

}
