package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerLevel generated by hbm2java
 */
@Entity
@Table(name = "customer_level", catalog = "wuyitech")
public class CustomerLevel implements java.io.Serializable {

	private Long id;
	private Integer level;
	private String name;
	private String state;
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<PromotionCustomerlevelRelation> promotionCustomerlevelRelations = new HashSet<PromotionCustomerlevelRelation>(
			0);

	public CustomerLevel() {
	}

	public CustomerLevel(Integer level, String name, String state,
			Set<Customer> customers,
			Set<PromotionCustomerlevelRelation> promotionCustomerlevelRelations) {
		this.level = level;
		this.name = name;
		this.state = state;
		this.customers = customers;
		this.promotionCustomerlevelRelations = promotionCustomerlevelRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state", length = 20)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerLevel")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerLevel")
	public Set<PromotionCustomerlevelRelation> getPromotionCustomerlevelRelations() {
		return this.promotionCustomerlevelRelations;
	}

	public void setPromotionCustomerlevelRelations(
			Set<PromotionCustomerlevelRelation> promotionCustomerlevelRelations) {
		this.promotionCustomerlevelRelations = promotionCustomerlevelRelations;
	}

}
