package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeePaymentRequest generated by hbm2java
 */
@Entity
@Table(name = "fee_payment_request", catalog = "wuyitech")
public class FeePaymentRequest implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private HouseMessage houseMessage;
	private String type;
	private String targetAccount;
	private String targetDepartment;
	private BigDecimal amount;
	private String state;
	private String orderId;
	private Date createDate;
	private String processState;

	public FeePaymentRequest() {
	}

	public FeePaymentRequest(Customer customer, HouseMessage houseMessage,
			String type, String targetAccount, String targetDepartment,
			BigDecimal amount, String state, String orderId, Date createDate,
			String processState) {
		this.customer = customer;
		this.houseMessage = houseMessage;
		this.type = type;
		this.targetAccount = targetAccount;
		this.targetDepartment = targetDepartment;
		this.amount = amount;
		this.state = state;
		this.orderId = orderId;
		this.createDate = createDate;
		this.processState = processState;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "house_message_id")
	public HouseMessage getHouseMessage() {
		return this.houseMessage;
	}

	public void setHouseMessage(HouseMessage houseMessage) {
		this.houseMessage = houseMessage;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "target_account", length = 45)
	public String getTargetAccount() {
		return this.targetAccount;
	}

	public void setTargetAccount(String targetAccount) {
		this.targetAccount = targetAccount;
	}

	@Column(name = "target_department", length = 45)
	public String getTargetDepartment() {
		return this.targetDepartment;
	}

	public void setTargetDepartment(String targetDepartment) {
		this.targetDepartment = targetDepartment;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "order_id", length = 45)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "process_state", length = 45)
	public String getProcessState() {
		return this.processState;
	}

	public void setProcessState(String processState) {
		this.processState = processState;
	}

}
