package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GoodsSkuAttributeValue generated by hbm2java
 */
@Entity
@Table(name = "goods_sku_attribute_value", catalog = "wuyitech")
public class GoodsSkuAttributeValue implements java.io.Serializable {

	private Long id;
	private GoodsSku goodsSku;
	private Long skuAttributeId;
	private String value;
	private String optionalImage;

	public GoodsSkuAttributeValue() {
	}

	public GoodsSkuAttributeValue(GoodsSku goodsSku) {
		this.goodsSku = goodsSku;
	}

	public GoodsSkuAttributeValue(GoodsSku goodsSku, Long skuAttributeId,
			String value, String optionalImage) {
		this.goodsSku = goodsSku;
		this.skuAttributeId = skuAttributeId;
		this.value = value;
		this.optionalImage = optionalImage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_sku_id", nullable = false)
	public GoodsSku getGoodsSku() {
		return this.goodsSku;
	}

	public void setGoodsSku(GoodsSku goodsSku) {
		this.goodsSku = goodsSku;
	}

	@Column(name = "sku_attribute_id")
	public Long getSkuAttributeId() {
		return this.skuAttributeId;
	}

	public void setSkuAttributeId(Long skuAttributeId) {
		this.skuAttributeId = skuAttributeId;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "optional_image")
	public String getOptionalImage() {
		return this.optionalImage;
	}

	public void setOptionalImage(String optionalImage) {
		this.optionalImage = optionalImage;
	}

}
