package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GoodsSku generated by hbm2java
 */
@Entity
@Table(name = "goods_sku", catalog = "wuyitech")
public class GoodsSku implements java.io.Serializable {

	private Long id;
	private Goods goods;
	private String skuNo;
	private BigDecimal price;
	private BigDecimal listPrice;
	private String skuAttributeStr;
	private Set<PromotionSkuRelation> promotionSkuRelations = new HashSet<PromotionSkuRelation>(
			0);
	private Set<OrderGoodsRelation> orderGoodsRelations = new HashSet<OrderGoodsRelation>(
			0);
	private Set<CustomerCollectGoods> customerCollectGoodses = new HashSet<CustomerCollectGoods>(
			0);
	private Set<GoodsSkuAttributeValue> goodsSkuAttributeValues = new HashSet<GoodsSkuAttributeValue>(
			0);
	private Set<PropertyFee> propertyFees = new HashSet<PropertyFee>(0);

	public GoodsSku() {
	}

	public GoodsSku(Goods goods, String skuNo, BigDecimal price,
			BigDecimal listPrice, String skuAttributeStr,
			Set<PromotionSkuRelation> promotionSkuRelations,
			Set<OrderGoodsRelation> orderGoodsRelations,
			Set<CustomerCollectGoods> customerCollectGoodses,
			Set<GoodsSkuAttributeValue> goodsSkuAttributeValues,
			Set<PropertyFee> propertyFees) {
		this.goods = goods;
		this.skuNo = skuNo;
		this.price = price;
		this.listPrice = listPrice;
		this.skuAttributeStr = skuAttributeStr;
		this.promotionSkuRelations = promotionSkuRelations;
		this.orderGoodsRelations = orderGoodsRelations;
		this.customerCollectGoodses = customerCollectGoodses;
		this.goodsSkuAttributeValues = goodsSkuAttributeValues;
		this.propertyFees = propertyFees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_id")
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@Column(name = "sku_no")
	public String getSkuNo() {
		return this.skuNo;
	}

	public void setSkuNo(String skuNo) {
		this.skuNo = skuNo;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "list_price", precision = 10)
	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	@Column(name = "sku_attribute_str")
	public String getSkuAttributeStr() {
		return this.skuAttributeStr;
	}

	public void setSkuAttributeStr(String skuAttributeStr) {
		this.skuAttributeStr = skuAttributeStr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsSku")
	public Set<PromotionSkuRelation> getPromotionSkuRelations() {
		return this.promotionSkuRelations;
	}

	public void setPromotionSkuRelations(
			Set<PromotionSkuRelation> promotionSkuRelations) {
		this.promotionSkuRelations = promotionSkuRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsSku")
	public Set<OrderGoodsRelation> getOrderGoodsRelations() {
		return this.orderGoodsRelations;
	}

	public void setOrderGoodsRelations(
			Set<OrderGoodsRelation> orderGoodsRelations) {
		this.orderGoodsRelations = orderGoodsRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsSku")
	public Set<CustomerCollectGoods> getCustomerCollectGoodses() {
		return this.customerCollectGoodses;
	}

	public void setCustomerCollectGoodses(
			Set<CustomerCollectGoods> customerCollectGoodses) {
		this.customerCollectGoodses = customerCollectGoodses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsSku")
	public Set<GoodsSkuAttributeValue> getGoodsSkuAttributeValues() {
		return this.goodsSkuAttributeValues;
	}

	public void setGoodsSkuAttributeValues(
			Set<GoodsSkuAttributeValue> goodsSkuAttributeValues) {
		this.goodsSkuAttributeValues = goodsSkuAttributeValues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goodsSku")
	public Set<PropertyFee> getPropertyFees() {
		return this.propertyFees;
	}

	public void setPropertyFees(Set<PropertyFee> propertyFees) {
		this.propertyFees = propertyFees;
	}

}
