package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods", catalog = "wuyitech")
public class Goods implements java.io.Serializable {

	private Long id;
	private String name;
	private String description;
	private Boolean isDiscount;
	private String mainImage;
	private String state;
	private Date createDate;
	private Date updateDate;
	private Boolean hasShippingFee;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<GoodsCategoryRelation> goodsCategoryRelations = new HashSet<GoodsCategoryRelation>(
			0);
	private Set<GoodsSku> goodsSkus = new HashSet<GoodsSku>(0);
	private Set<Tag> tags = new HashSet<Tag>(0);
	private Set<PromotionGoodsRelation> promotionGoodsRelations = new HashSet<PromotionGoodsRelation>(
			0);
	private Set<GoodsSupplierRelation> goodsSupplierRelations = new HashSet<GoodsSupplierRelation>(
			0);
	private Set<GoodsSkuAttributeRelation> goodsSkuAttributeRelations = new HashSet<GoodsSkuAttributeRelation>(
			0);
	private Set<GoodsMedia> goodsMedias = new HashSet<GoodsMedia>(0);

	public Goods() {
	}

	public Goods(String name) {
		this.name = name;
	}

	public Goods(String name, String description, Boolean isDiscount,
			String mainImage, String state, Date createDate, Date updateDate,
			Boolean hasShippingFee, Set<Comment> comments,
			Set<GoodsCategoryRelation> goodsCategoryRelations,
			Set<GoodsSku> goodsSkus, Set<Tag> tags,
			Set<PromotionGoodsRelation> promotionGoodsRelations,
			Set<GoodsSupplierRelation> goodsSupplierRelations,
			Set<GoodsSkuAttributeRelation> goodsSkuAttributeRelations,
			Set<GoodsMedia> goodsMedias) {
		this.name = name;
		this.description = description;
		this.isDiscount = isDiscount;
		this.mainImage = mainImage;
		this.state = state;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.hasShippingFee = hasShippingFee;
		this.comments = comments;
		this.goodsCategoryRelations = goodsCategoryRelations;
		this.goodsSkus = goodsSkus;
		this.tags = tags;
		this.promotionGoodsRelations = promotionGoodsRelations;
		this.goodsSupplierRelations = goodsSupplierRelations;
		this.goodsSkuAttributeRelations = goodsSkuAttributeRelations;
		this.goodsMedias = goodsMedias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "is_discount")
	public Boolean getIsDiscount() {
		return this.isDiscount;
	}

	public void setIsDiscount(Boolean isDiscount) {
		this.isDiscount = isDiscount;
	}

	@Column(name = "main_image")
	public String getMainImage() {
		return this.mainImage;
	}

	public void setMainImage(String mainImage) {
		this.mainImage = mainImage;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "has_shipping_fee")
	public Boolean getHasShippingFee() {
		return this.hasShippingFee;
	}

	public void setHasShippingFee(Boolean hasShippingFee) {
		this.hasShippingFee = hasShippingFee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<GoodsCategoryRelation> getGoodsCategoryRelations() {
		return this.goodsCategoryRelations;
	}

	public void setGoodsCategoryRelations(
			Set<GoodsCategoryRelation> goodsCategoryRelations) {
		this.goodsCategoryRelations = goodsCategoryRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<GoodsSku> getGoodsSkus() {
		return this.goodsSkus;
	}

	public void setGoodsSkus(Set<GoodsSku> goodsSkus) {
		this.goodsSkus = goodsSkus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<Tag> getTags() {
		return this.tags;
	}

	public void setTags(Set<Tag> tags) {
		this.tags = tags;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<PromotionGoodsRelation> getPromotionGoodsRelations() {
		return this.promotionGoodsRelations;
	}

	public void setPromotionGoodsRelations(
			Set<PromotionGoodsRelation> promotionGoodsRelations) {
		this.promotionGoodsRelations = promotionGoodsRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<GoodsSupplierRelation> getGoodsSupplierRelations() {
		return this.goodsSupplierRelations;
	}

	public void setGoodsSupplierRelations(
			Set<GoodsSupplierRelation> goodsSupplierRelations) {
		this.goodsSupplierRelations = goodsSupplierRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<GoodsSkuAttributeRelation> getGoodsSkuAttributeRelations() {
		return this.goodsSkuAttributeRelations;
	}

	public void setGoodsSkuAttributeRelations(
			Set<GoodsSkuAttributeRelation> goodsSkuAttributeRelations) {
		this.goodsSkuAttributeRelations = goodsSkuAttributeRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "goods")
	public Set<GoodsMedia> getGoodsMedias() {
		return this.goodsMedias;
	}

	public void setGoodsMedias(Set<GoodsMedia> goodsMedias) {
		this.goodsMedias = goodsMedias;
	}

}
