package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GoodsSkuAttributeRelation generated by hbm2java
 */
@Entity
@Table(name = "goods_sku_attribute_relation", catalog = "wuyitech")
public class GoodsSkuAttributeRelation implements java.io.Serializable {

	private Long id;
	private Goods goods;
	private SkuAttribute skuAttribute;

	public GoodsSkuAttributeRelation() {
	}

	public GoodsSkuAttributeRelation(Goods goods, SkuAttribute skuAttribute) {
		this.goods = goods;
		this.skuAttribute = skuAttribute;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_id")
	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sku_attribute_id")
	public SkuAttribute getSkuAttribute() {
		return this.skuAttribute;
	}

	public void setSkuAttribute(SkuAttribute skuAttribute) {
		this.skuAttribute = skuAttribute;
	}

}
