package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HouseMessage generated by hbm2java
 */
@Entity
@Table(name = "house_message", catalog = "wuyitech")
public class HouseMessage implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private LivingArea livingArea;
	private String bulidNo;
	private String unitNo;
	private String houseNo;
	private String ownerPhone;
	private String ownerName;
	private BigDecimal area;
	private Set<FeePaymentRequest> feePaymentRequests = new HashSet<FeePaymentRequest>(
			0);
	private Set<PropertyRequest> propertyRequests = new HashSet<PropertyRequest>(
			0);

	public HouseMessage() {
	}

	public HouseMessage(Customer customer, LivingArea livingArea,
			String bulidNo, String unitNo, String houseNo, String ownerPhone,
			String ownerName, BigDecimal area,
			Set<FeePaymentRequest> feePaymentRequests,
			Set<PropertyRequest> propertyRequests) {
		this.customer = customer;
		this.livingArea = livingArea;
		this.bulidNo = bulidNo;
		this.unitNo = unitNo;
		this.houseNo = houseNo;
		this.ownerPhone = ownerPhone;
		this.ownerName = ownerName;
		this.area = area;
		this.feePaymentRequests = feePaymentRequests;
		this.propertyRequests = propertyRequests;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "living_area_id")
	public LivingArea getLivingArea() {
		return this.livingArea;
	}

	public void setLivingArea(LivingArea livingArea) {
		this.livingArea = livingArea;
	}

	@Column(name = "bulid_no", length = 45)
	public String getBulidNo() {
		return this.bulidNo;
	}

	public void setBulidNo(String bulidNo) {
		this.bulidNo = bulidNo;
	}

	@Column(name = "unit_no", length = 45)
	public String getUnitNo() {
		return this.unitNo;
	}

	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	@Column(name = "house_no", length = 45)
	public String getHouseNo() {
		return this.houseNo;
	}

	public void setHouseNo(String houseNo) {
		this.houseNo = houseNo;
	}

	@Column(name = "owner_phone", length = 45)
	public String getOwnerPhone() {
		return this.ownerPhone;
	}

	public void setOwnerPhone(String ownerPhone) {
		this.ownerPhone = ownerPhone;
	}

	@Column(name = "owner_name", length = 45)
	public String getOwnerName() {
		return this.ownerName;
	}

	public void setOwnerName(String ownerName) {
		this.ownerName = ownerName;
	}

	@Column(name = "area", precision = 10)
	public BigDecimal getArea() {
		return this.area;
	}

	public void setArea(BigDecimal area) {
		this.area = area;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "houseMessage")
	public Set<FeePaymentRequest> getFeePaymentRequests() {
		return this.feePaymentRequests;
	}

	public void setFeePaymentRequests(Set<FeePaymentRequest> feePaymentRequests) {
		this.feePaymentRequests = feePaymentRequests;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "houseMessage")
	public Set<PropertyRequest> getPropertyRequests() {
		return this.propertyRequests;
	}

	public void setPropertyRequests(Set<PropertyRequest> propertyRequests) {
		this.propertyRequests = propertyRequests;
	}

}
