package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IndexRecommendList generated by hbm2java
 */
@Entity
@Table(name = "index_recommend_list", catalog = "wuyitech")
public class IndexRecommendList implements java.io.Serializable {

	private Long id;
	private String type;
	private Long relateId;
	private String indexImageUrl;
	private Integer displayOrder;
	private Date startDate;
	private Date endDate;

	public IndexRecommendList() {
	}

	public IndexRecommendList(String type, Long relateId, String indexImageUrl,
			Integer displayOrder, Date startDate, Date endDate) {
		this.type = type;
		this.relateId = relateId;
		this.indexImageUrl = indexImageUrl;
		this.displayOrder = displayOrder;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "relate_id")
	public Long getRelateId() {
		return this.relateId;
	}

	public void setRelateId(Long relateId) {
		this.relateId = relateId;
	}

	@Column(name = "index_image_url")
	public String getIndexImageUrl() {
		return this.indexImageUrl;
	}

	public void setIndexImageUrl(String indexImageUrl) {
		this.indexImageUrl = indexImageUrl;
	}

	@Column(name = "display_order")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
