package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LivingArea generated by hbm2java
 */
@Entity
@Table(name = "living_area", catalog = "wuyitech")
public class LivingArea implements java.io.Serializable {

	private Long id;
	private City city;
	private String name;
	private String description;
	private BigDecimal propertyPrice;
	private String phone;
	private String state;
	private Set<Worker> workers = new HashSet<Worker>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<HouseMessage> houseMessages = new HashSet<HouseMessage>(0);
	private Set<OrderInfo> orderInfos = new HashSet<OrderInfo>(0);

	public LivingArea() {
	}

	public LivingArea(City city, String name, String description,
			BigDecimal propertyPrice, String phone, String state,
			Set<Worker> workers, Set<Customer> customers,
			Set<HouseMessage> houseMessages, Set<OrderInfo> orderInfos) {
		this.city = city;
		this.name = name;
		this.description = description;
		this.propertyPrice = propertyPrice;
		this.phone = phone;
		this.state = state;
		this.workers = workers;
		this.customers = customers;
		this.houseMessages = houseMessages;
		this.orderInfos = orderInfos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_id")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "property_price", precision = 10)
	public BigDecimal getPropertyPrice() {
		return this.propertyPrice;
	}

	public void setPropertyPrice(BigDecimal propertyPrice) {
		this.propertyPrice = propertyPrice;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livingArea")
	public Set<Worker> getWorkers() {
		return this.workers;
	}

	public void setWorkers(Set<Worker> workers) {
		this.workers = workers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livingArea")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livingArea")
	public Set<HouseMessage> getHouseMessages() {
		return this.houseMessages;
	}

	public void setHouseMessages(Set<HouseMessage> houseMessages) {
		this.houseMessages = houseMessages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livingArea")
	public Set<OrderInfo> getOrderInfos() {
		return this.orderInfos;
	}

	public void setOrderInfos(Set<OrderInfo> orderInfos) {
		this.orderInfos = orderInfos;
	}

}
