package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderInfo generated by hbm2java
 */
@Entity
@Table(name = "order_info", catalog = "wuyitech")
public class OrderInfo implements java.io.Serializable {

	private Long id;
	private City city;
	private Customer customer;
	private LivingArea livingArea;
	private String orderName;
	private String orderSn;
	private String customerNote;
	private String orderState;
	private String phone;
	private Date payDate;
	private BigDecimal shippingFee;
	private BigDecimal orderAmount;
	private Date shippingDate;
	private Date createDate;
	private String state;
	private Set<SubOrderInfo> subOrderInfos = new HashSet<SubOrderInfo>(0);
	private Set<Payment> payments = new HashSet<Payment>(0);

	public OrderInfo() {
	}

	public OrderInfo(City city, Customer customer, LivingArea livingArea,
			String orderName, String orderSn, String customerNote,
			String orderState, String phone, Date payDate,
			BigDecimal shippingFee, BigDecimal orderAmount, Date shippingDate,
			Date createDate, String state, Set<SubOrderInfo> subOrderInfos,
			Set<Payment> payments) {
		this.city = city;
		this.customer = customer;
		this.livingArea = livingArea;
		this.orderName = orderName;
		this.orderSn = orderSn;
		this.customerNote = customerNote;
		this.orderState = orderState;
		this.phone = phone;
		this.payDate = payDate;
		this.shippingFee = shippingFee;
		this.orderAmount = orderAmount;
		this.shippingDate = shippingDate;
		this.createDate = createDate;
		this.state = state;
		this.subOrderInfos = subOrderInfos;
		this.payments = payments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_id")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "living_area_id")
	public LivingArea getLivingArea() {
		return this.livingArea;
	}

	public void setLivingArea(LivingArea livingArea) {
		this.livingArea = livingArea;
	}

	@Column(name = "order_name")
	public String getOrderName() {
		return this.orderName;
	}

	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	@Column(name = "order_sn", length = 45)
	public String getOrderSn() {
		return this.orderSn;
	}

	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	@Column(name = "customer_note")
	public String getCustomerNote() {
		return this.customerNote;
	}

	public void setCustomerNote(String customerNote) {
		this.customerNote = customerNote;
	}

	@Column(name = "order_state", length = 45)
	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_date", length = 19)
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	@Column(name = "shipping_fee", precision = 10)
	public BigDecimal getShippingFee() {
		return this.shippingFee;
	}

	public void setShippingFee(BigDecimal shippingFee) {
		this.shippingFee = shippingFee;
	}

	@Column(name = "order_amount", precision = 10)
	public BigDecimal getOrderAmount() {
		return this.orderAmount;
	}

	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shipping_date", length = 19)
	public Date getShippingDate() {
		return this.shippingDate;
	}

	public void setShippingDate(Date shippingDate) {
		this.shippingDate = shippingDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderInfo")
	public Set<SubOrderInfo> getSubOrderInfos() {
		return this.subOrderInfos;
	}

	public void setSubOrderInfos(Set<SubOrderInfo> subOrderInfos) {
		this.subOrderInfos = subOrderInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderInfo")
	public Set<Payment> getPayments() {
		return this.payments;
	}

	public void setPayments(Set<Payment> payments) {
		this.payments = payments;
	}

}
