package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PromotionSkuRelation generated by hbm2java
 */
@Entity
@Table(name = "promotion_sku_relation", catalog = "wuyitech")
public class PromotionSkuRelation implements java.io.Serializable {

	private Long id;
	private GoodsSku goodsSku;
	private Promotion promotion;

	public PromotionSkuRelation() {
	}

	public PromotionSkuRelation(GoodsSku goodsSku, Promotion promotion) {
		this.goodsSku = goodsSku;
		this.promotion = promotion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_sku_id")
	public GoodsSku getGoodsSku() {
		return this.goodsSku;
	}

	public void setGoodsSku(GoodsSku goodsSku) {
		this.goodsSku = goodsSku;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id")
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

}
