package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PromotionCustomerlevelRelation generated by hbm2java
 */
@Entity
@Table(name = "promotion_customerlevel_relation", catalog = "wuyitech")
public class PromotionCustomerlevelRelation implements java.io.Serializable {

	private Long id;
	private CustomerLevel customerLevel;
	private Promotion promotion;

	public PromotionCustomerlevelRelation() {
	}

	public PromotionCustomerlevelRelation(CustomerLevel customerLevel,
			Promotion promotion) {
		this.customerLevel = customerLevel;
		this.promotion = promotion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_level_id")
	public CustomerLevel getCustomerLevel() {
		return this.customerLevel;
	}

	public void setCustomerLevel(CustomerLevel customerLevel) {
		this.customerLevel = customerLevel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "promotion_id")
	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

}
