package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promotion generated by hbm2java
 */
@Entity
@Table(name = "promotion", catalog = "wuyitech")
public class Promotion implements java.io.Serializable {

	private Long id;
	private Date createTime;
	private Date updateTime;
	private String state;
	private String name;
	private String iamgeUrl;
	private Date startDate;
	private Date endDate;
	private String areaType;
	private String userType;
	private String operationType;
	private String operation;
	private BigDecimal operationNumber;
	private String targetType;
	private Long targetId;
	private Integer minBuy;
	private Integer maxBuy;
	private Boolean customerOnce;
	private Integer deductReward;
	private BigDecimal minOrderAmount;
	private Integer availableTimes;
	private Set<PromotionGoodsRelation> promotionGoodsRelations = new HashSet<PromotionGoodsRelation>(
			0);
	private Set<PromotionCustomerRelation> promotionCustomerRelations = new HashSet<PromotionCustomerRelation>(
			0);
	private Set<PromotionCustomerlevelRelation> promotionCustomerlevelRelations = new HashSet<PromotionCustomerlevelRelation>(
			0);
	private Set<PromotionCategoryRelation> promotionCategoryRelations = new HashSet<PromotionCategoryRelation>(
			0);
	private Set<PromotionSkuRelation> promotionSkuRelations = new HashSet<PromotionSkuRelation>(
			0);

	public Promotion() {
	}

	public Promotion(
			Date createTime,
			Date updateTime,
			String state,
			String name,
			String iamgeUrl,
			Date startDate,
			Date endDate,
			String areaType,
			String userType,
			String operationType,
			String operation,
			BigDecimal operationNumber,
			String targetType,
			Long targetId,
			Integer minBuy,
			Integer maxBuy,
			Boolean customerOnce,
			Integer deductReward,
			BigDecimal minOrderAmount,
			Integer availableTimes,
			Set<PromotionGoodsRelation> promotionGoodsRelations,
			Set<PromotionCustomerRelation> promotionCustomerRelations,
			Set<PromotionCustomerlevelRelation> promotionCustomerlevelRelations,
			Set<PromotionCategoryRelation> promotionCategoryRelations,
			Set<PromotionSkuRelation> promotionSkuRelations) {
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.state = state;
		this.name = name;
		this.iamgeUrl = iamgeUrl;
		this.startDate = startDate;
		this.endDate = endDate;
		this.areaType = areaType;
		this.userType = userType;
		this.operationType = operationType;
		this.operation = operation;
		this.operationNumber = operationNumber;
		this.targetType = targetType;
		this.targetId = targetId;
		this.minBuy = minBuy;
		this.maxBuy = maxBuy;
		this.customerOnce = customerOnce;
		this.deductReward = deductReward;
		this.minOrderAmount = minOrderAmount;
		this.availableTimes = availableTimes;
		this.promotionGoodsRelations = promotionGoodsRelations;
		this.promotionCustomerRelations = promotionCustomerRelations;
		this.promotionCustomerlevelRelations = promotionCustomerlevelRelations;
		this.promotionCategoryRelations = promotionCategoryRelations;
		this.promotionSkuRelations = promotionSkuRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "iamge_url", length = 45)
	public String getIamgeUrl() {
		return this.iamgeUrl;
	}

	public void setIamgeUrl(String iamgeUrl) {
		this.iamgeUrl = iamgeUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "area_type", length = 45)
	public String getAreaType() {
		return this.areaType;
	}

	public void setAreaType(String areaType) {
		this.areaType = areaType;
	}

	@Column(name = "user_type", length = 45)
	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	@Column(name = "operation_type", length = 45)
	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	@Column(name = "operation", length = 45)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "operation_number", precision = 10)
	public BigDecimal getOperationNumber() {
		return this.operationNumber;
	}

	public void setOperationNumber(BigDecimal operationNumber) {
		this.operationNumber = operationNumber;
	}

	@Column(name = "target_type", length = 45)
	public String getTargetType() {
		return this.targetType;
	}

	public void setTargetType(String targetType) {
		this.targetType = targetType;
	}

	@Column(name = "target_id")
	public Long getTargetId() {
		return this.targetId;
	}

	public void setTargetId(Long targetId) {
		this.targetId = targetId;
	}

	@Column(name = "min_buy")
	public Integer getMinBuy() {
		return this.minBuy;
	}

	public void setMinBuy(Integer minBuy) {
		this.minBuy = minBuy;
	}

	@Column(name = "max_buy")
	public Integer getMaxBuy() {
		return this.maxBuy;
	}

	public void setMaxBuy(Integer maxBuy) {
		this.maxBuy = maxBuy;
	}

	@Column(name = "customer_once")
	public Boolean getCustomerOnce() {
		return this.customerOnce;
	}

	public void setCustomerOnce(Boolean customerOnce) {
		this.customerOnce = customerOnce;
	}

	@Column(name = "deduct_reward")
	public Integer getDeductReward() {
		return this.deductReward;
	}

	public void setDeductReward(Integer deductReward) {
		this.deductReward = deductReward;
	}

	@Column(name = "min_order_amount", precision = 10)
	public BigDecimal getMinOrderAmount() {
		return this.minOrderAmount;
	}

	public void setMinOrderAmount(BigDecimal minOrderAmount) {
		this.minOrderAmount = minOrderAmount;
	}

	@Column(name = "available_times")
	public Integer getAvailableTimes() {
		return this.availableTimes;
	}

	public void setAvailableTimes(Integer availableTimes) {
		this.availableTimes = availableTimes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionGoodsRelation> getPromotionGoodsRelations() {
		return this.promotionGoodsRelations;
	}

	public void setPromotionGoodsRelations(
			Set<PromotionGoodsRelation> promotionGoodsRelations) {
		this.promotionGoodsRelations = promotionGoodsRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionCustomerRelation> getPromotionCustomerRelations() {
		return this.promotionCustomerRelations;
	}

	public void setPromotionCustomerRelations(
			Set<PromotionCustomerRelation> promotionCustomerRelations) {
		this.promotionCustomerRelations = promotionCustomerRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionCustomerlevelRelation> getPromotionCustomerlevelRelations() {
		return this.promotionCustomerlevelRelations;
	}

	public void setPromotionCustomerlevelRelations(
			Set<PromotionCustomerlevelRelation> promotionCustomerlevelRelations) {
		this.promotionCustomerlevelRelations = promotionCustomerlevelRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionCategoryRelation> getPromotionCategoryRelations() {
		return this.promotionCategoryRelations;
	}

	public void setPromotionCategoryRelations(
			Set<PromotionCategoryRelation> promotionCategoryRelations) {
		this.promotionCategoryRelations = promotionCategoryRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "promotion")
	public Set<PromotionSkuRelation> getPromotionSkuRelations() {
		return this.promotionSkuRelations;
	}

	public void setPromotionSkuRelations(
			Set<PromotionSkuRelation> promotionSkuRelations) {
		this.promotionSkuRelations = promotionSkuRelations;
	}

}
