package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PropertyFeeHistory generated by hbm2java
 */
@Entity
@Table(name = "property_fee_history", catalog = "wuyitech")
public class PropertyFeeHistory implements java.io.Serializable {

	private Long id;
	private PropertyFee propertyFee;
	private Worker worker;
	private Date createDate;
	private String state;
	private BigDecimal paymentPrice;
	private BigDecimal discountNumber;

	public PropertyFeeHistory() {
	}

	public PropertyFeeHistory(PropertyFee propertyFee, Worker worker,
			Date createDate, String state, BigDecimal paymentPrice,
			BigDecimal discountNumber) {
		this.propertyFee = propertyFee;
		this.worker = worker;
		this.createDate = createDate;
		this.state = state;
		this.paymentPrice = paymentPrice;
		this.discountNumber = discountNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "property_fee_id")
	public PropertyFee getPropertyFee() {
		return this.propertyFee;
	}

	public void setPropertyFee(PropertyFee propertyFee) {
		this.propertyFee = propertyFee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "worker_id")
	public Worker getWorker() {
		return this.worker;
	}

	public void setWorker(Worker worker) {
		this.worker = worker;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "payment_price", precision = 10)
	public BigDecimal getPaymentPrice() {
		return this.paymentPrice;
	}

	public void setPaymentPrice(BigDecimal paymentPrice) {
		this.paymentPrice = paymentPrice;
	}

	@Column(name = "discount_number", precision = 10)
	public BigDecimal getDiscountNumber() {
		return this.discountNumber;
	}

	public void setDiscountNumber(BigDecimal discountNumber) {
		this.discountNumber = discountNumber;
	}

}
