package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PropertyFee generated by hbm2java
 */
@Entity
@Table(name = "property_fee", catalog = "wuyitech")
public class PropertyFee implements java.io.Serializable {

	private Long id;
	private Customer customer;
	private GoodsSku goodsSku;
	private String year;
	private BigDecimal listPrice;
	private BigDecimal price;
	private String state;
	private String paymentMethod;
	private BigDecimal realpayPrice;
	private Set<PropertyFeeHistory> propertyFeeHistories = new HashSet<PropertyFeeHistory>(
			0);

	public PropertyFee() {
	}

	public PropertyFee(Customer customer, GoodsSku goodsSku, String year,
			BigDecimal listPrice, BigDecimal price, String state,
			String paymentMethod, BigDecimal realpayPrice,
			Set<PropertyFeeHistory> propertyFeeHistories) {
		this.customer = customer;
		this.goodsSku = goodsSku;
		this.year = year;
		this.listPrice = listPrice;
		this.price = price;
		this.state = state;
		this.paymentMethod = paymentMethod;
		this.realpayPrice = realpayPrice;
		this.propertyFeeHistories = propertyFeeHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "goods_sku_id")
	public GoodsSku getGoodsSku() {
		return this.goodsSku;
	}

	public void setGoodsSku(GoodsSku goodsSku) {
		this.goodsSku = goodsSku;
	}

	@Column(name = "year", length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	@Column(name = "list_price", precision = 10)
	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	@Column(name = "price", precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "payment_method", length = 45)
	public String getPaymentMethod() {
		return this.paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	@Column(name = "realpay_price", precision = 10)
	public BigDecimal getRealpayPrice() {
		return this.realpayPrice;
	}

	public void setRealpayPrice(BigDecimal realpayPrice) {
		this.realpayPrice = realpayPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "propertyFee")
	public Set<PropertyFeeHistory> getPropertyFeeHistories() {
		return this.propertyFeeHistories;
	}

	public void setPropertyFeeHistories(
			Set<PropertyFeeHistory> propertyFeeHistories) {
		this.propertyFeeHistories = propertyFeeHistories;
	}

}
