package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RewardHistory generated by hbm2java
 */
@Entity
@Table(name = "reward_history", catalog = "wuyitech")
public class RewardHistory implements java.io.Serializable {

	private Long id;
	private RewardAccount rewardAccount;
	private String description;
	private Date updateDate;
	private String operation;
	private BigDecimal operationNumber;

	public RewardHistory() {
	}

	public RewardHistory(RewardAccount rewardAccount, String description,
			Date updateDate, String operation, BigDecimal operationNumber) {
		this.rewardAccount = rewardAccount;
		this.description = description;
		this.updateDate = updateDate;
		this.operation = operation;
		this.operationNumber = operationNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reward_account_id")
	public RewardAccount getRewardAccount() {
		return this.rewardAccount;
	}

	public void setRewardAccount(RewardAccount rewardAccount) {
		this.rewardAccount = rewardAccount;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "operation", length = 45)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "operation_number", precision = 10)
	public BigDecimal getOperationNumber() {
		return this.operationNumber;
	}

	public void setOperationNumber(BigDecimal operationNumber) {
		this.operationNumber = operationNumber;
	}

}
