package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubOrderInfo generated by hbm2java
 */
@Entity
@Table(name = "sub_order_info", catalog = "wuyitech")
public class SubOrderInfo implements java.io.Serializable {

	private Long id;
	private OrderInfo orderInfo;
	private String subOrderName;
	private String orderSn;
	private String customerNote;
	private String orderState;
	private Long livingAreaId;
	private Long cityId;
	private String phone;
	private Date payDate;
	private BigDecimal subOrderAmount;
	private Date shippingDate;
	private Date createDate;
	private Date updateDate;
	private Set<OrderGoodsRelation> orderGoodsRelations = new HashSet<OrderGoodsRelation>(
			0);
	private Set<OrderAction> orderActions = new HashSet<OrderAction>(0);

	public SubOrderInfo() {
	}

	public SubOrderInfo(OrderInfo orderInfo) {
		this.orderInfo = orderInfo;
	}

	public SubOrderInfo(OrderInfo orderInfo, String subOrderName,
			String orderSn, String customerNote, String orderState,
			Long livingAreaId, Long cityId, String phone, Date payDate,
			BigDecimal subOrderAmount, Date shippingDate, Date createDate,
			Date updateDate, Set<OrderGoodsRelation> orderGoodsRelations,
			Set<OrderAction> orderActions) {
		this.orderInfo = orderInfo;
		this.subOrderName = subOrderName;
		this.orderSn = orderSn;
		this.customerNote = customerNote;
		this.orderState = orderState;
		this.livingAreaId = livingAreaId;
		this.cityId = cityId;
		this.phone = phone;
		this.payDate = payDate;
		this.subOrderAmount = subOrderAmount;
		this.shippingDate = shippingDate;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.orderGoodsRelations = orderGoodsRelations;
		this.orderActions = orderActions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_info_id", nullable = false)
	public OrderInfo getOrderInfo() {
		return this.orderInfo;
	}

	public void setOrderInfo(OrderInfo orderInfo) {
		this.orderInfo = orderInfo;
	}

	@Column(name = "sub_order_name")
	public String getSubOrderName() {
		return this.subOrderName;
	}

	public void setSubOrderName(String subOrderName) {
		this.subOrderName = subOrderName;
	}

	@Column(name = "order_sn", length = 45)
	public String getOrderSn() {
		return this.orderSn;
	}

	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	@Column(name = "customer_note")
	public String getCustomerNote() {
		return this.customerNote;
	}

	public void setCustomerNote(String customerNote) {
		this.customerNote = customerNote;
	}

	@Column(name = "order_state", length = 45)
	public String getOrderState() {
		return this.orderState;
	}

	public void setOrderState(String orderState) {
		this.orderState = orderState;
	}

	@Column(name = "living_area_id")
	public Long getLivingAreaId() {
		return this.livingAreaId;
	}

	public void setLivingAreaId(Long livingAreaId) {
		this.livingAreaId = livingAreaId;
	}

	@Column(name = "city_id")
	public Long getCityId() {
		return this.cityId;
	}

	public void setCityId(Long cityId) {
		this.cityId = cityId;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_date", length = 19)
	public Date getPayDate() {
		return this.payDate;
	}

	public void setPayDate(Date payDate) {
		this.payDate = payDate;
	}

	@Column(name = "sub_order_amount", precision = 10)
	public BigDecimal getSubOrderAmount() {
		return this.subOrderAmount;
	}

	public void setSubOrderAmount(BigDecimal subOrderAmount) {
		this.subOrderAmount = subOrderAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "shipping_date", length = 19)
	public Date getShippingDate() {
		return this.shippingDate;
	}

	public void setShippingDate(Date shippingDate) {
		this.shippingDate = shippingDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subOrderInfo")
	public Set<OrderGoodsRelation> getOrderGoodsRelations() {
		return this.orderGoodsRelations;
	}

	public void setOrderGoodsRelations(
			Set<OrderGoodsRelation> orderGoodsRelations) {
		this.orderGoodsRelations = orderGoodsRelations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subOrderInfo")
	public Set<OrderAction> getOrderActions() {
		return this.orderActions;
	}

	public void setOrderActions(Set<OrderAction> orderActions) {
		this.orderActions = orderActions;
	}

}
