package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name = "supplier", catalog = "wuyitech")
public class Supplier implements java.io.Serializable {

	private Long id;
	private String name;
	private String username;
	private String password;
	private String state;
	private Date createDate;
	private Set<GoodsSupplierRelation> goodsSupplierRelations = new HashSet<GoodsSupplierRelation>(
			0);

	public Supplier() {
	}

	public Supplier(String name, String username, String password,
			String state, Date createDate,
			Set<GoodsSupplierRelation> goodsSupplierRelations) {
		this.name = name;
		this.username = username;
		this.password = password;
		this.state = state;
		this.createDate = createDate;
		this.goodsSupplierRelations = goodsSupplierRelations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplier")
	public Set<GoodsSupplierRelation> getGoodsSupplierRelations() {
		return this.goodsSupplierRelations;
	}

	public void setGoodsSupplierRelations(
			Set<GoodsSupplierRelation> goodsSupplierRelations) {
		this.goodsSupplierRelations = goodsSupplierRelations;
	}

}
