package wuyi.model.po;

// Generated May 5, 2015 9:16:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Worker generated by hbm2java
 */
@Entity
@Table(name = "worker", catalog = "wuyitech")
public class Worker implements java.io.Serializable {

	private Long id;
	private LivingArea livingArea;
	private String name;
	private String role;
	private String state;
	private String username;
	private String password;
	private Boolean loginAble;
	private String phone;
	private Set<PropertyRequestHistory> propertyRequestHistories = new HashSet<PropertyRequestHistory>(
			0);
	private Set<PropertyFeeHistory> propertyFeeHistories = new HashSet<PropertyFeeHistory>(
			0);

	public Worker() {
	}

	public Worker(LivingArea livingArea, String name, String role,
			String state, String username, String password, Boolean loginAble,
			String phone, Set<PropertyRequestHistory> propertyRequestHistories,
			Set<PropertyFeeHistory> propertyFeeHistories) {
		this.livingArea = livingArea;
		this.name = name;
		this.role = role;
		this.state = state;
		this.username = username;
		this.password = password;
		this.loginAble = loginAble;
		this.phone = phone;
		this.propertyRequestHistories = propertyRequestHistories;
		this.propertyFeeHistories = propertyFeeHistories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "living_area_id")
	public LivingArea getLivingArea() {
		return this.livingArea;
	}

	public void setLivingArea(LivingArea livingArea) {
		this.livingArea = livingArea;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "username", length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "login_able")
	public Boolean getLoginAble() {
		return this.loginAble;
	}

	public void setLoginAble(Boolean loginAble) {
		this.loginAble = loginAble;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "worker")
	public Set<PropertyRequestHistory> getPropertyRequestHistories() {
		return this.propertyRequestHistories;
	}

	public void setPropertyRequestHistories(
			Set<PropertyRequestHistory> propertyRequestHistories) {
		this.propertyRequestHistories = propertyRequestHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "worker")
	public Set<PropertyFeeHistory> getPropertyFeeHistories() {
		return this.propertyFeeHistories;
	}

	public void setPropertyFeeHistories(
			Set<PropertyFeeHistory> propertyFeeHistories) {
		this.propertyFeeHistories = propertyFeeHistories;
	}

}
